
if(WL_PACKAGE_MANAGER MATCHES "find")
    if(NOT TARGET wl-deps)
        add_library(wl-deps INTERFACE)
    endif()
    find_package(Eigen3 REQUIRED)
    find_package(spdlog REQUIRED)
    find_package(fmt    REQUIRED)
    find_package(h5pp   REQUIRED)
    find_package(CLI11  REQUIRED)
    target_link_libraries(wl-deps INTERFACE Eigen3::Eigen spdlog::spdlog fmt::fmt h5pp::h5pp CLI11::CLI11)
endif()